### ISSUE TITLE
no response when update user account

### ISSUE THREAD

**Issue by viney91** [tipimail/tipimail-php-library#3]
in Users/UsersService.php......

.....
public function updateUsername($id, $username) {
.....
`$this->tipimail->putData($this->url . '/' . $id, $data);`
// **return** was ommited = **return** $this->tipimail.....
}

DO THE SAME FOR FUNCTIONS : updateFirstName, updateLastName & resetPassword

**Comment by tipim4il** [comment]
Thank you for your comment, we've updated our documentation.
Please use try catch
