### ISSUE TITLE
stats by tags return all tags !!!

### ISSUE THREAD

**Issue by viney91** [tipimail/tipimail-php-library#4]
according to the doc : 

`$provider->getStatisticsService()->getSendsByTag($dateBegin, $dateEnd, $froms, $tags, $apiKeys);`

but actually it is : 

`$provider->getStatisticsService()->getSendsByTag($dateBegin, $dateEnd, $froms, $apiKeys, $tags);`

.. issue for each stats docs...

**Comment by tipim4il** [comment]
Thanks you for your comment, we've udpated our documentation
